/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 world_cup_trophy.gltf --transform 
Files: world_cup_trophy.gltf [4.28MB] > C:\Users\39343\Desktop\world_cup_trophy\world_cup_trophy-transformed.glb [328.12KB] (92%)
Author: Andrew Lebedev (https://sketchfab.com/Andrew_Lebedev_CGI)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/world-cup-trophy-e28e9b2d3c374303974bd9898bbb2a64
Title: World cup trophy
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/world_cup_trophy-transformed.glb')
  return (
    <group {...props} dispose={null} scale={[3,3,3]}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.Trophy_Mtl} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Trophy_base_Mtl} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Wooden_Box_Mtl} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Tabeles_and_Rivets_Mtl} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/world_cup_trophy-transformed.glb')
